// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function GetTransactions() {
  return window['go']['main']['App']['GetTransactions']();
}

export function SaveTransaction(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveTransaction'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateTransaction(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateTransaction'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
